Кондрашова Анастасия
НПМбд-01-19
LU-разложение 

Импортируем нужные нам библиотеки

In [1]:
import numpy as np

Функция «LU_decomposition» раскладывает квадратную матрицу А на матрицы L (нижняя треугольная) и U (верхняя треугольная)

In [3]:
def LU_decomposition(A):

    n = A.shape[0]
    
    L = np.identity(n)
    U = A.copy()
    
    for i in range(n):
            
        multiplier = U[i + 1 :, i] / U[i, i]
        L[i + 1 :, i] += multiplier
        multiplier.resize(multiplier.size, 1)
        U[i + 1 :] -= multiplier * U[i]
        
    return L, U

Задаём квадратную матрицу 3x3

In [4]:
A = np.array([[10, 20, 30.], 
              [0, -50, 60.], 
              [70, 40, 90.]])

Проверяем работу функции

In [5]:
LU_decomposition(A)

(array([[1., 0., 0.],
        [0., 1., 0.],
        [7., 2., 1.]]),
 array([[  10.,   20.,   30.],
        [   0.,  -50.,   60.],
        [   0.,    0., -240.]]))

Проверяем А = LU

In [6]:
L, U = LU_decomposition(A)

A == L.dot(U)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Функция «SLAE_LU» находит решение СЛАУ с помощью LU-разложения. Функция принимает матрицу А и вектор-столбец х, возвращает вектор-столбец решений с округлением до сотых

In [7]:
# y = Ux
# b = Ly

def SLAE_LU(A, b): 
    
    L, U = LU_decomposition(A)
    
    n = L.shape[0]
    
    y = np.zeros_like(b, dtype=np.double) # Возвращает массив нулей той же формы и типа, что и заданный массив
    
    y[0] = b[0] / L[0, 0] # y1 = b1/l11
    
    for i in range(n):
        y[i] = (b[i] - np.dot(L[i,:i], y[:i])) / L[i,i] # (bi - sum(from 1 to i-1)(Lij*yj))/Lii

    m = L.shape[0]
    
    x = np.zeros_like(y, dtype=np.double)
    
    x[-1] = y[-1] / U[-1, -1] # # ym = bm/lm
    
    for i in range(m-2, -1, -1):
        x[i] = (y[i] - np.dot(U[i,i:], x[i:])) / U[i,i] # (yi - sum(from i+1 to m)(Uij*xj))/Uii

    return np.round(x, 2)

Задаём вектор-столбец

In [8]:
b = np.array([[30], 
              [20], 
              [10]])

Проверяем работу функции

In [9]:
SLAE_LU(A, b)

array([[-1.6],
       [ 0.8],
       [ 1. ]])

Проверяем, совпадает ли результат при использовании linalg.solve

In [10]:
np.round(np.linalg.solve(A, b), 2)

array([[-1.6],
       [ 0.8],
       [ 1. ]])

Проверяем, совпадает ли результат при использовании lu_factor и lu_solve библиотеки scipy.linalg

In [11]:

from scipy.linalg import lu_factor, lu_solve

np.round(lu_solve(lu_factor(A), b), 2)

array([[-1.6],
       [ 0.8],
       [ 1. ]])